FROM hostname.lan.home:65432/ubuntu:jammy
LABEL maintainer littlewing

RUN apt update && \
 apt --assume-yes --no-install-recommends full-upgrade \
  ffmpeg
RUN rm --recursive --force /var/lib/apt/lists/*

COPY script/entrypoint.sh /

VOLUME ["/var/log", "/etc/localtime:ro"]
ENTRYPOINT ["/entrypoint.sh"]
